config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :solutions
  end

   root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :solutions

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :solutions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, except:[:new, :index, :create]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      flash[:notice] = 'Project created successfully'
      redirect_to @project
    else
      flast[:error] = 'Something went wrong'
      render :new
    end

  end

  def edit

  end

  def show
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :update
    end
  end

  def destroy
  end


  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :user_id)
  end


end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :find_solution, except:[:new, :create, :index]

  def index
    @solutions = Solution.all
  end

  def show

  end

  def new
    puts "PARAMS == #{params}"
    @solution = Solution.new
    @project = Project.find(params[:project_id])
  end

  def create
    @solution = current_user.solutions.new(solution_params)

    puts "solutions == #{@solutions}\n\n\n"
    if @solution.save
      flash[:notice] = 'Solutions Created'
      redirect_to projects_path
    end


  end

  def edit
  end

  def update
  end

  def destroy

  end

  private

  def solution_params
    params.require(:solution).permit(:url, :user_id, :project_id)
  end

  def find_solution
    @solution = Solution.find(param[:id])
  end

  def build_solution_hash(params)
    {
     url: params['solution']['url'],
     user_id: current_user.id,
     project_id: params['project_id'].to_i
    }
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApprenticeLab03</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Home', root_path %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/projects/edit.html.erb
<%= render partial: 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<table>
<thead>
  <tr>
    <th>id</th>
    <th>Title</th>
    <th>description</th>
  </tr>
</thead>
<% @projects.each do |project| %>
  <tr>
    <td><%= project.id %></td>
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project_path(project) %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Fork', new_project_solution_path(project.id) %></td>
  </tr>
<% end %>
</table>
<hr>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<%= render partial: 'form' %>

app/views/projects/show.html.erb
<%= @project.title %>
<%= @project.description %>

<%= link_to 'Home', root_path %>

app/views/solutions/_form.html.erb
<%= form_for [@project, @solution] do |f| %>
<p>
  <%= f.label :URL%>
  <%= f.text_field :url %>
</p>

<p>
  <%= f.submit %>
</p>
  
<% end %>

app/views/solutions/edit.html.erb
<h1>Solutions#edit</h1>
<p>Find me in app/views/solutions/edit.html.erb</p>

app/views/solutions/index.html.erb
<h1>Solutions#index</h1>
<p>Find me in app/views/solutions/index.html.erb</p>

app/views/solutions/new.html.erb
<h1>Solution for <%= @project.title %> </h1>

<%= render partial: 'form' %>